version: 2

jobs:
  build_and_test:
    docker:
      - image: circleci/python:latest

    steps:
      - checkout
      - run: pip install --user mypy pylint pytest
      - run: ./test


workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
